blockQueue: 'no'
nameOverride: ''
fullnameOverride: ''
otelHttpEndpoint: suse-opentelemetry-collector.monitoring.svc.cluster.local:4318
traceEnabled: true
metricsEnabled: false
image: ravan/mockroservice:0.0.24
resources:
  requests:
    memory: '15Mi'
    cpu: '18m'
  limits:
    memory: '18Mi'
    cpu: '20m'

printQueueResourcesWhenBlocking:
  requests:
    memory: '50Mi'
    cpu: '16m'
  limits:
    memory: '55Mi'
    cpu: '18m'
