apiVersion: v1
kind: ConfigMap
metadata:
  name: printer-3d-cm
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.toml: |
     
     
     # General configuration
     port = 8080
     address = "0.0.0.0"
     serviceName = "3D Printer"
     logLevel = "info"
     
     [logging]
     logOnCall = 1
     before = "Service is open for business!"

     # Endpoints
     [[endpoints]]
     uri = "/print-job"
     delay = "300ms"
     errorOnCall = 0
     body.status = "success"
     body.msg = "Print job completed"
     
     # Route to Printing Queue
     [[endpoints.routes]]
     uri = "printing-queue/get"
     delay = "20ms"
     stopOnFail = true

     [[endpoints]]
     uri = "/maintenance"
     delay = "50ms"
     errorOnCall = 40
     body.status = "success"
     body.msg = "Maintenance check passed"
     
     [endpoints.logging]
     before = "Processing [[.Endpoint.Uri]] request"
     beforeLevel = "Info"
     after = "Completed [[.Endpoint.Uri]] request"
     afterLevel = "Info"
     
     
     
     
     [otel.trace]
     enabled = {{.Values.traceEnabled}}
     tracer-name = "3d-printer"
     http-endpoint = "{{.Values.otelHttpEndpoint}}"
     insecure = true

     [otel.metrics]
     enabled = {{.Values.metricsEnabled}}
     http-endpoint = "{{.Values.otelHttpEndpoint}}" 
     insecure = true
