apiVersion: v1
kind: ConfigMap
metadata:
  name: build-a-dino-cm
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.toml: |
     # General configuration
     port = 8080
     address = "0.0.0.0"
     serviceName = "Build-a-Dino"
     logLevel = "info"

     [logging]
     logOnCall = 1
     before = "Service is open for business!"
     
     # Endpoints
     [[endpoints]]
     uri = "/design"
     delay = "100ms"
     errorOnCall = 0
     body.status = "success"
     body.msg = "Dino design ready"


     # Route to AI Model
     [[endpoints.routes]]
     uri = "ai-sim-service/train"
     delay = "20ms"
     stopOnFail = false
     
     [[endpoints]]
     uri = "/order"
     delay = "50ms"
     errorOnCall = 0
     body.status = "success"
     body.msg = "Order placed for dino build"
     
     # Route to AI Model
     [[endpoints.routes]]
     uri = "ai-sim-service/predict"
     delay = "20ms"
     stopOnFail = true
     
     # Route to Printing Service
     [[endpoints.routes]]
     uri = "printing-service/start-print"
     delay = "30ms"
     stopOnFail = true
     
     [endpoints.logging]
     logOnCall = 1
     before = "Processing [[.Endpoint.Uri]] request"
     beforeLevel = "Info"
     
     
     [otel.trace]
     enabled = {{.Values.traceEnabled}}
     tracer-name = "build-a-dino"
     http-endpoint = "{{.Values.otelHttpEndpoint}}"
     insecure = true

     [otel.metrics]
     enabled = {{.Values.metricsEnabled}}
     http-endpoint = "{{.Values.otelHttpEndpoint}}" 
     insecure = true
