apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiosk-web
  labels:
    service: kiosk-web
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kiosk-web
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        service: kiosk-web 
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/frontend-cm.yaml") . | sha256sum}}'
    spec:
      containers:
      - name: kiosk-web
        image: {{.Values.image}}
        env:
        - name: CONFIG_FILE
          value: /etc/app/config.toml
        ports:
        - containerPort: 8080
        resources:
          {{- toYaml .Values.resources | nindent 12 }} 
        volumeMounts:
        - name: config-volume
          mountPath: /etc/app
      volumes:
      - name: config-volume
        configMap:
          name: kiosk-web-cm
          items:
          - key: config.toml
            path: config.toml
