apiVersion: v1
kind: ConfigMap
metadata:
  name: printing-service-cm
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.toml: |
     
     
     # General configuration
     port = 8080
     address = "0.0.0.0"
     serviceName = "Printing Service"
     logLevel = "info"

     [logging]
     logOnCall = 1
     before = "Service is open for business!"
     
     # Endpoints
     [[endpoints]]
     uri = "/start-print"
     delay = "200ms"
     errorOnCall = 0
     body.status = "success"
     body.msg = "3D print job started"

     # Route to Printing Queue
     [[endpoints.routes]]
     uri = "printing-queue/put"
     delay = "50ms"
     stopOnFail = true
     

     [[endpoints]]
     uri = "/check-status"
     delay = "10ms"
     errorOnCall = 25
     body.status = "success"
     body.msg = "Print status retrieved"
     
     [endpoints.logging]
     before = "Processing [[.Endpoint.Uri]] request"
     beforeLevel = "Info"
     after = "Completed [[.Endpoint.Uri]] request"
     afterLevel = "Info"
     
     
     
     
     [otel.trace]
     enabled = {{.Values.traceEnabled}}
     tracer-name = "printing-service"
     http-endpoint = "{{.Values.otelHttpEndpoint}}"
     insecure = true

     [otel.metrics]
     enabled = {{.Values.metricsEnabled}}
     http-endpoint = "{{.Values.otelHttpEndpoint}}" 
     insecure = true
