apiVersion: apps/v1
kind: Deployment
metadata:
  name: printing-queue
  labels:
    service: printing-queue
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: printing-queue
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        service: printing-queue 
      annotations:
        checksum/config: '{{ include (print $.Template.BasePath "/printing-queue-cm.yaml") . | sha256sum}}'
        {{- if eq .Values.blockQueue "yes"}}
        change/by: "Lead Performasaurus" 
        change/type: "Premature optimization that should work."
        {{- end}}
    spec:
      containers:
      - name: printing-queue
        image: {{.Values.image}}
        env:
        - name: CONFIG_FILE
          value: /etc/app/config.toml
        ports:
        - containerPort: 8080
        {{ if eq .Values.blockQueue "yes" }}
        resources:
          {{- toYaml .Values.printQueueResourcesWhenBlocking | nindent 12 }}   
        {{ else }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }} 
        {{ end }} 
        volumeMounts:
        - name: config-volume
          mountPath: /etc/app
      volumes:
      - name: config-volume
        configMap:
          name: printing-queue-cm
          items:
          - key: config.toml
            path: config.toml
