apiVersion: v1
kind: ConfigMap
metadata:
  name: simservice-cm
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.toml: |
     
     
     # Endpoints
     [[endpoints]]
     uri = "/predict"
     delay = "10ms"
     errorOnCall = 0
     body.status = "success"
     body.msg = "Prediction generated"

     [logging]
     logOnCall = 1
     before = "Service is open for business!"
     
     [[endpoints]]
     uri = "/train"
     delay = "500ms"
     errorOnCall = 0
     body.status = "success"
     body.msg = "Model training completed"
     
     [endpoints.logging]
     before = "Processing [[.Endpoint.Uri]] request"
     beforeLevel = "Info"
     after = "Completed [[.Endpoint.Uri]] request"
     afterLevel = "Info"
     
     
     [otel.trace]
     enabled = {{.Values.traceEnabled}}
     tracer-name = "simservice"
     http-endpoint = "{{.Values.otelHttpEndpoint}}"
     insecure = true

     [otel.metrics]
     enabled = {{.Values.metricsEnabled}}
     http-endpoint = "{{.Values.otelHttpEndpoint}}" 
     insecure = true
